---
stages:
- name: Build dhir nginx
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: master
    dir_name: null
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy dhir nginx
  inputs:
  - type: job
    stage: Build dhir nginx
    job: Build
    dir_name: null
  properties:
  - name: BLUE_GREEN
    type: text_area
    value: ${DEPLOY_SCRIPT}
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      
      echo "${BLUE_GREEN}" > blue_green.sh
      chmod +x blue_green.sh
      ./blue_greene.sh -n dhir-nginx-devops -d mybluemix.net -f bluemix/dev-manifest.yml
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
