---
stages:
- name: Build frontend
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: ibm-devops
    dir_name: null
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.10.48, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.10.48/bin:$PATH
      # To use Node.js 0.12.7, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.4.5, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
      # To use Node.js 6.7.0, uncomment the following line:
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      npm install && npm start && rm -r -f  node_modules
- name: Test frontend
  inputs:
  - type: job
    stage: Build frontend
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Test
    type: tester
    script: |-
      #!/bin/bash
      # invoke tests here
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      # Run unit-tests
      npm install && npm run test-unit
    enable_tests: true
    test_file_pattern: test-*.xml
- name: Deploy frontend
  inputs:
  - type: job
    stage: Build frontend
    job: Build
    dir_name: null
  properties:
  - name: ICON_DOMAIN
    type: text
    value: ${ICON_DOMAIN}
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: "${DEPLOY_SCRIPT}\n deploy "cf push cf push \"${CF_APP}\" -d \"${ICON_DOMAIN}\" -n nwhu -n gbhu -f bluemix/dev-manifest.yml"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
