---
stages:
- name: Build server and worker
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: ibm-devops
    dir_name: null
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
      #!/bin/bash
      # your script here
      git log --format="commit=%H" -n 1 >> ./commit.properties
- name: Test server
  inputs:
  - type: job
    stage: Build server and worker
    job: Build
    dir_name: null
  jobs:
  - name: Tests
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME1}
    script: |
      #!/bin/bash

      # Prepare testing environment
      export TESTING_ENV=testing

      # Install the dependencies
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      npm install

      # Get VCAP env setup
      bash scripts/services.sh
      node scripts/env.js

      # Run the tests
      npm test
- name: Deploy server and worker
  inputs:
  - type: job
    stage: Build server and worker
    job: Build
    dir_name: null
  jobs:
  - name: Deploy server
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME1}
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -d mybluemix.net -n icon-server-devops -f bluemix/dev-main-manifest.yml
  - name: Deploy worker
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME2}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}" -d bluemix.net -n icon-server-devops -f bluemix/dev-worker-manifest.yml
- name: Tagging
  inputs:
  - type: job
    stage: Build server and worker
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: GIT_USER
    type: secure
  - name: GIT_PASS
    type: secure
  - name: ICON_DOMAIN
    type: text
    value: ${ICON_DOMAIN}
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: "#!/bin/bash\n# your script here\nls\necho  \"get commit number\" \nCOMMIT_NUMBER=`bash\
      \ scripts/read_properties.sh commit.properties commit`\n\necho \"clone repo\"\
      \ngit clone https://$GIT_USER:$GIT_PASS@github.com/MOHLTC11/icon-r2-backend.git\n\
      cd icon-r2-backend\n\necho \"check out $COMMIT_NUMBER\"\ngit checkout ${COMMIT_NUMBER}\n\
      \n\nTAG=\"build-${BUILD_NUMBER}-$(date +%Y-%m-%d)\"\necho \"Creating tag: $TAG\"\
      \ngit tag $TAG\n\n#git push --tags\n\n"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
