---
stages:
- name: Build ICON Kibana
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: master
    dir_name: null
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: 
- name: Deploy ICON Kibana
  inputs:
  - type: job
    stage: Build ICON Kibana
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: BLUE_GREEN
    type: text_area
    value: ${DEPLOY_SCRIPT}

  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      
      echo "${BLUE_GREEN}" > blue_green.sh
      chmod +x blue_green.sh
      ./blue_green.sh -f bluemix/dev-manifest.yml -n icon-kibana-devops -d mybluemix.net
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
